### ISSUE TITLE
Validate a set of files by glob pattern

### ISSUE THREAD

**Issue by sim642** [cardinalby/schema-validator-action#1]
E.g. validate all files matching the glob pattern `conf/**.json` against a particular schema.

**Comment by cardinalby** [comment]
Hi! Thanks for the feedback.

As I see in other actions, a more common form of pointing to multiple files is a comma-separated list of file names. Probably, it can contain glob patterns as well.

Unfortunately, I don't have the capacity for this now but will definitely look at it later. Meanwhile, you are welcome to create a pull request if you decide to implement it by yourself.

**Comment by cardinalby** [comment]
@sim642 Proposed feature was implemented in version `1.1.0`. It's also available under `@v1` and `@master`.
I made both `|` separators and glob patterns allowed in `file` input.
