### ISSUE TITLE
please allow extraFormats setting

### ISSUE THREAD

**Issue by Bluscream** [cardinalby/schema-validator-action#15]

**Comment by cardinalby** [comment]
Hi! Can't read your mind, pls add a description and and some examples.

**Comment by Bluscream** [comment]
In your own [docs](https://github.com/cardinalby/schema-validator-action?tab=readme-ov-file#-mode-default-value-default) you link to the relevant page at https://github.com/ExodusMovement/schemasafe/blob/master/doc/Options.md

> extraFormats — false by default.
Enable extra built-in non-standard formats, see [formats.js](https://github.com/ExodusMovement/schemasafe/blob/master/src/formats.js).

if i understand the setting correctly; it will allow usage of more `"format": ` options like `uri`, `uuid`, [`boolean`](https://github.com/Bluscream/AMPTemplates/actions/runs/10434803032) etc generated by https://app.quicktype.io/schema for example. That way i won't have to do cursed regex patterns like [this](https://github.com/Bluscream/AMPTemplates/blob/dev/schemas/manifest.schema.json#L33) anymore

**Comment by cardinalby** [comment]
took a look, it's enabled in the action

**Comment by Bluscream** [comment]
mhmm okay that's weird, moved this request up the chain then https://github.com/ExodusMovement/schemasafe/issues/186

Thanks for taking a look
