### ISSUE TITLE
Validate against `$schema` from file itself

### ISSUE THREAD

**Issue by sim642** [cardinalby/schema-validator-action#2]
Instead of requiring the schema to be specified in the action, if the file to be validated itself provides a `$schema` key, then it should be automatically validated against that.

**Comment by cardinalby** [comment]
Hi! Thanks for the feedback.

Your suggestion looks pretty reasonable. Unfortunately, I don't have the capacity for this now but will definitely look at it later. Meanwhile, you are welcome to create a pull request if you decide to implement it by yourself.

**Comment by cardinalby** [comment]
@sim642 Proposed feature was implemented in version `1.1.0`. It's also available under `@v1` and `@master`.
