### ISSUE TITLE
This repository contains vulnerabilities detected by Dependabot

### ISSUE THREAD

**Issue by ravikumar2026** [cardinalby/schema-validator-action#7]
Please fix the Dependabot vulnerabilities on a open source repository and retrigger the workflow.
Vulnerabilities: [ { "createdAt": "2023-06-21T21:53:57Z", "dismissedAt": null, "securityVulnerability": { "package": { "name": "yaml" }, "severity": "HIGH" } } ]

**Comment by cardinalby** [comment]
I fixed the critical vulnerability, but didn't mange to fix many others :(
