### ISSUE TITLE
Cannot validate with https://json.schemastore.org/chrome-manifest with schema-validator-action@v2/v3

### ISSUE THREAD

**Issue by djahandarie** [cardinalby/schema-validator-action#8]
Ever since v2/v3, I can't seem to use this action to validate https://json.schemastore.org/chrome-manifest , even if I set `mode: lax`.

Namely, I get the following error:
```
Run cardinalby/schema-validator-action@8407573c2627c5159428cf9fa3770d13b2360a27
  with:
    file: ext/manifest.json
    schema: https://json.schemastore.org/chrome-manifest.json
    mode: lax
    fileParser: auto
Schema loaded from https://json.schemastore.org/chrome-manifest.json has undefined type:
Contents of 'https://json.schemastore.org/chrome-manifest.json' has been parsed as json object
Contents of 'ext/manifest.json' has been parsed as json object
Error: Unrecognized format used: "match-pattern" at https://json.schemastore.org/chrome-manifest.json#
Error: Failed because of schema error
```

Judging by https://github.com/SchemaStore/schemastore/blob/5c03d06b2c30f1000afa172f5853e8fa7b2d12d6/src/schema-validation.json#L417, it seems like they do something extra for adding exceptions for these unknown formats in their own validation pipeline.

I'm not sure what the optimal way to handle this is with schemasafe options, but presumably one of ones related to 'formats' [here](https://github.com/ExodusMovement/schemasafe/blob/master/doc/Options.md#options-for-relaxing-coherence-checks:~:text=requireSchema%20is%20on.-,formatAssertion,-%E2%80%94%20true%20by)? 

> formatAssertion — true by default (false by default when mode = 'spec' and $schema is draft2019-09 or later).
> 
> Switching it to false will disable format assertions, essentially making them not affect the result of validation at all, i.e. validation would pass regardless of all format strings in the schema.
> 
> That (false) behaviour is specified as default in the upstream since draft2019-09, but not followed here, unless mode is set to 'spec', due to being potentially dangereous/unsafe and missing expected validation.
> 
> For more info, see upstream documentation and upstream changelog.
> 
> formats — {} by default.
> Additional formats to use.
> 
> weakFormats — true in 'default' and 'lax'/'spec' modes, false in 'strong' mode by default.
> Add support for formats deemed potentially weak (currently, only RegExp).
> 
> extraFormats — false by default.
> Enable extra built-in non-standard formats, see formats.js.

I'd appreciate an extra input for the action that makes it possible to validate with schemastore's chrome-manfiest file.

**Comment by cardinalby** [comment]
Hi!
I was able to make schema-sage ignore unknown formats by passing
```
formats: {
    'match-pattern': (input: string) => true,
    "content-security-policy": (input: string) => true,
    'glob-pattern': (input: string) => true,
    'mime-type': (input: string) => true,
    'permission': (input: string) => true,
}
```
to the options, but then another error appears on this schema: `Unexpected token 'const'`. 

`const` seems to be standard keyword that is not supported by schema-safe :( 

When I was looking for a JS validation library I tried several and schema-safe was the most promising and the clearest interface. Maybe it's time to look for another one to use under the hood, but I don't have much time to investigate that at the moment. 

As a temporal solution you can try to copy the schema and manually remove problematic instructions or replace them with supported ones. For example, `const` can be replaced by `enum` if I'm not wrong.

Do you believe I should just add an input like `ignored_formats` for that? Nobody will pass own implementations of formats to the action I think. Another option can be creating additional action that strips these instructions from a schema and replaces `const` by `enum` for example to not overcomplicate the validation action itself.

**Comment by djahandarie** [comment]
Thanks for investigating 🙏 . Yeah, an ignore-formats input would work fine — but I was not expecting the const issue. I will consider opening an issue on the schemasafe side to if there is no way to configure it to not error.
As for a separate action, I think this sort of patching is minimal enough that it would fit in this action, but up to you!

**Comment by cardinalby** [comment]
@djahandarie Hi again

The `const` issue was probably fixed in one of the recent schemasafe version, I updated schemasafe version in the action.

To deal with unknown formats try using new `fixSchemas: true` action input that removes unknown for schemasafe "format" instructions from a schema.

Please let me know if it works for you

**Comment by djahandarie** [comment]
It worked, and `mode: lax` wasn't even required. :sunglasses:

Thank you so much!
